name: Push to feature branch

on:
  push:
    branches:
      - 'master'
      - 'develop' #debug

 
env:
    #TF_LOG: INFO  #debug only
    TF_INPUT: false

jobs: 
    terraform-core:
        environment: demogcp
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform/core
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Authenticate to GCP
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: "1.7.5"

            - name: Terraform Init
              id: init
              run: terraform init 

            - name: Terraform Validate
              id: validate
              # Run even if formatting fails
              if: success() || failure()
              run: terraform validate

            - name: Terraform Apply
              id: plan
              run: terraform apply --auto-approve

    terraform-services:
        environment: demogcp
        runs-on: ubuntu-latest
        needs: terraform-core
        defaults:
          run:
              shell: bash
              working-directory: ./terraform/services
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Authenticate to GCP
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: "1.7.5"

          - name: Terraform Init
            id: init
            run: terraform init 

          - name: Terraform Validate
            id: validate
            # Run even if formatting fails
            if: success() || failure()
            run: terraform validate

          - name: Terraform Apply
            id: plan
            run: terraform apply --auto-approve

    
    terraform-application:
        environment: demogcp
        runs-on: ubuntu-latest
        needs: terraform-services
        defaults:
          run:
              shell: bash
              working-directory: ./terraform/application
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Authenticate to GCP
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: "1.7.5"

          - name: Terraform Init
            id: init
            run: terraform init 

          - name: Terraform Validate
            id: validate
            # Run even if formatting fails
            if: success() || failure()
            run: terraform validate

          - name: Terraform Apply
            id: plan
            run: terraform apply --auto-approve
